services:
  judgehost-0:
    container_name: judgehost-0
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-0
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      - DAEMON_ID=0
      - JUDGEDAEMON_PASSWORD="<paste the password here>"

  judgehost-1:
    container_name: judgehost-1
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      - DAEMON_ID=1
      - JUDGEDAEMON_PASSWORD: "<paste the password here>"

  judgehost-2:
    container_name: judgehost-2
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      - DAEMON_ID=2
      - JUDGEDAEMON_PASSWORD="<paste the password here>"

  judgehost-3:
    container_name: judgehost-3
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-3
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    environment:
      - DAEMON_ID=3
      - JUDGEDAEMON_PASSWORD="<paste the password here>"

networks:
  domjudge:
    name: netnet
    external: true